# Workflow for building and deploying a Hugo site to S3
name: Deploy Hugo site to S3

on:
  # Runs on 'git push', targeting the default branch
  push:
    branches: ["main"]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
# Sets permissions of the GITHUB_TOKEN to allow deployment to S3
permissions:
  contents: read
  id-token: write

# Default to bash
defaults:
  run:
    shell: bash

jobs:
# Deployment job
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checks-out this repository under $GITHUB_WORKSPACE, so the job can access it
      - name: "Checkout repo"
        uses: actions/checkout@v4
      - name: "Abort if any trace of development build is detected (it should be a staging build)."
        run: |
          [grep -qr 'localhost:1313' * ] && echo "::error::Development build detected." && exit 1
      - name: "Replace 'staging' Google tags with 'production' equivalents"
        run: find . -type f -exec sed -i~ 's/B3ECKP96EL/DPHXLK5VEW/g' '{}' '+'
      - name: "Replace 'staging' URL with 'production' equivalent"
        run: find . -type f -exec sed -i~ 's/test\.steinitzchessclub\.co\.za/www.steinitzchessclub.co.za/g' '{}' '+'
      - name: "Remove ~ suffixed temp files created as part of the above SED operation."
        run: find . -name "*~" -exec rm {} +
      - name: Remove hidden files and dirs recursively
        run: find . -name '.[a-zA-Z0-9]*' | xargs rm -fr 
      - name: "Remove other unneeded files"
        run: rm CNAME
      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: arn:aws:iam::881490093474:role/SteinitzWebsite_S3Deployer # this will be the ARN of the role you created in the "Creating a Role for deployment" step.
          role-session-name: GithubActions-SteinitzWebsite
          mask-aws-account-id: true          
      - name: "Sync to S3"
        id: deployment
        run: aws s3 sync ./ s3://${{ vars.BUCKET_NAME }} --delete --cache-control max-age=31536000
      - name: "Cloudfront Invalidation"
        id: flushcache
        run: aws cloudfront create-invalidation --distribution-id ${{ vars.CF_DISTRIBUTION_ID }} --paths "/*"
